# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievments',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
