# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='category/'),
        ),
    ]
